services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: mci_orders
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123

    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: